name: eif6d
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pytorch=1.10.1
  - torchvision=0.11.2
  - cudatoolkit=11.3
  - pip:
    - opencv-python
    
   
