name: eif6d
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pytorch=1.10.1
  - torchvision=0.11.2
  - cudatoolkit=11.3
  - pillow=8.3.1
  - matplotlib=3.3.4
  - tqdm=4.64.1
  - pip:
    - opencv-python==4.5.5.60
    
   
